sudo: false

language: c

matrix:
  include:
    - env: FLAGS="--flag static-text:text --flag static-text:bytestring --flag static-text:vector" ARGS=""
      compiler: ": #stack default"
      addons: {apt: {packages: [libgmp-dev]}}
    - env: FLAGS="--flag static-text:text --flag static-text:bytestring --flag static-text:vector" ARGS="--stack-yaml=stack-previous.yaml"
      compiler: ": #stack previous"
      addons: {apt: {packages: [libgmp-dev]}}

before_install:
- unset CC
- mkdir -p $HOME/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
- curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s .
- stack $ARGS --install-ghc --no-terminal test $FLAGS --haddock --no-haddock-deps --pedantic

cache:
  directories:
  - $HOME/.stack
